dependencies:
- name: bdd-gh-1584909787
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1584909787
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-import-1584912004
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1584909787
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbrp-import-1584912004
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1584908709
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
